benchmark:
  script:
    - mkdir -p build/release
    - ls -la
    - cargo build --release && cp target/release/pgcontent ./content
    - ls -la
    - cd build/release
    - /uploader/uploader string-similarity-search ./contest
  tags:
    - submission
