[package]
name = "pgcontest"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
opt-level=3
debug=false
overflow-checks=false

[dependencies]
ascii = "1.1.0"
rayon = "1.6.0"
